.github/workflows/ci.yaml
lib/charms/hpc_libs/v0/slurm_ops.py
tests/integration/slurm_ops/test_manager.py
tests/unit/test_slurm_ops.py
tox.ini

A bit of magic on the test file to avoid having to repeat 4 times the exact same test code, but I think we can live with that 😬

test: add unit tests for `slurm_ops`

---

.editorconfig
.github/workflows/release-libs.yaml

Title gives it away, but this pull request sets up the `release-libs` workflow for `hpc-libs`. Pretty much the same thing as the the workflow from `storage-libs`.
I added a token to the repository secrets that will allow us to upload the `slurm_ops` library. It will expire while we are in The Hague for the Engineering Sprint in October. I'm very tempted to write us a tool like [`tokenator`](https://github.com/snapcrafters/tokenator) that enables us to bulk refresh our repo secrets so it's not this weird song and dance when we try to publish new updates to Charmhub :sweat_smile: 
I added a _.editorconfig_ file. Helps with consistency across IDE's. We can extend rules farther as we need to :smiley:

feat: add workflow for publishing libraries after merge

---

.github/workflows/release-libs.yaml

For some reason is looking for metadata.yaml file.

fix(ci): bump release-libraries to 2.6.1

---

lib/charms/hpc_libs/v0/slurm_ops.py
tests/integration/slurm_ops/test_manager.py
tests/unit/test_slurm_ops.py
tox.ini

This pull request enhances the API of `slurm_ops` to use composition and inheritance to build the Slurm service operations managers. This makes it easier for us to construct managers around `slurmctld`, `slurmd`, `slurmdbd`, and `slurmrestd` and share logic for configuration and service management between them. 
bulk update the configuration of slurmctld:
```python3
from charms.hpc_libs.v0.slurm_ops import SlurmManagerBase, ServiceType
slurmctld = SlurmManagerBase(ServiceType.SLURMCTLD)
slurmctld.config.set({"option1": "value1", "option2": "value2"})
```
set a new munge key:
```python3
from charms.hpc_libs.v0.slurm_ops import SlurmManagerBase, ServiceType
slurmd = SlurmManagerBase(ServiceType.SLURMD)
slurmd.munge.set_key("encodedmungekey")
slurmd.munge.restart()
```
start slurmrestd: …

feat!: use composition and inheritance to build service managers

---

lib/charms/hpc_libs/v0/is_container.py
tests/integration/is_container/test_is_container.py
tests/integration/test_hpc_libs.yaml
tests/unit/test_is_container.py

This pull request adds the small `is_container` charm library. This utility enables us to check if the current charm is running within a container using the [`systemd-detect-virt`](https://manpages.ubuntu.com/manpages/noble/en/man1/systemd-detect-virt.1.html) utility.
Why add this library? In multiple places we're using a utility like this - like both the Slurm and NFS operators - so it would be good to just have one source of truth for this method. We can also extend as necessary to detect multiple different container runtimes.

Add `is_container` charm library

---

lib/charms/hpc_libs/v0/slurm_ops.py
tests/unit/test_slurm_ops.py

feat: Add `SlurmOpsError` to `slurm_ops`

---

lib/charms/hpc_libs/v0/slurm_ops.py
tests/unit/test_slurm_ops.py

This pull request adds the ability to both bulk get and unset configuration options on slurm config objects. This functionality will be helpful for both if we want to reset the state of Slurm, and quickly get configuration information for various Slurm objects for comparison against new information received by the charms.
For example:
```python3
slurmctld = SlurmManagerBase(ServiceType.SLURMCTLD)
slurmctld.config.get()
slurmctld.config.unset()
```
* Fixes a bug with `.unset(...)`. If we use `snap unset ...` instead of `snap set ...`, we don't need to append the `!` exclamation point to the end of the key name. Whoopsies :cold_face:
* `ConfigurationManager` now takes a string in its constructor rather than a `ServiceType`. This makes it much easier to create configuration managers for …

feat: enable bulk getting and unsetting of configuration options

---

lib/charms/hpc_libs/v0/slurm_ops.py
tests/unit/test_slurm_ops.py

feat: add method to get the host name

---

lib/charms/hpc_libs/v0/slurm_ops.py

Adds the `PrometheusExporterManager` class for managing the operations of the Slurm prometheus exporter bundled with the Slurm snap.
`PrometheusExporterManager` inherits from `ServiceManager` so that it can enable, disable, and restart the exporter service. The exporter is exposed through the `exporter` attribute of `SlurmManagerBase`. This way we can use something like the following block of code to turn on the exporter after we have connected a COS deployment to Charmed HPC:
```python3
def _on_integration(self, _: Event) -> None:
"""Handler for when COS is integrated into cluster."""
...
self._manager.exporter.enable()
```
One thing we'll likely need to do in the future is that once we determine how we want to configure the prometheus exporter, we'll need to expose a config interface. …

feat: add prometheus exporter manager

---

dev-requirements.txt
lib/charms/hpc_libs/v0/slurm_ops.py
tests/integration/slurm_ops/test_manager.py
tests/unit/test_slurm_ops.py
tox.ini

This PR abstracts around the base package manager used.
The objective of this is to enable switching between snap packages and deb packages in a more composable way.

feat: abstract around base package manager

---

lib/charms/hpc_libs/v0/slurm_ops.py
tests/unit/test_slurm_ops.py

Fixes a bug where the script would throw when `check_output` throws an error, since the returned `stderr` would be a str instead of bytes.

fix: remove `decode` inside `_call`

---

dev-requirements.txt
lib/charms/hpc_libs/v0/slurm_ops.py
lib/charms/operator_libs_linux/v0/apt.py
tests/integration/slurm_ops/conftest.py
tests/integration/slurm_ops/test_manager.py
tests/integration/test_hpc_libs.yaml
tests/unit/test_slurm_ops.py

Implements an `AptManager` for `slurm_ops` that uses `apt` to install packages and `systemctl` to manage services.

feat: implement `AptManager` for `slurm_ops`

---

lib/charms/hpc_libs/v0/slurm_ops.py

Small PR to change exporter service name from `slurm-prometheus-exporter` to `prometheus-slurm-exporter` so that the service name is standard with other exporters packaged for Debian.
Closes #25

fix: slurm-prometheus-exporter -> prometheus-slurm-exporter

---

lib/charms/hpc_libs/v0/slurm_ops.py

Bumps the LIBPATCH version of `slurm_ops` to 7. Now that we have the deb manager and correct prometheus exporter service name, we can go zooooom in the Slurm charms with COS.

chore(vbump): bump LIBPATCH version to 7

---

lib/charms/hpc_libs/v0/slurm_ops.py
tests/unit/test_slurm_ops.py

This PR adds the static method `scontrol` to `_SlurmManagerBase`, and it cleans up the public exports of the slurm_ops charm library to just be `SlurmctldManager`, `SlurmdManager`, `SlurmdbdManager`, `SlurmrestdManager`, and `SlurmOpsError`.
Closes #29

feat(slurm_ops): add `scontrol` and clean up public exports

---

dev-requirements.txt
lib/charms/hpc_libs/v0/slurm_ops.py
tests/integration/slurm_ops/test_manager.py
tests/unit/test_slurm_ops.py

This PR enhances the configuration management interface and adds a configuration manager for the _cgroup.conf_ file. The configuration management interface is extended by adding the `load` and `dump` methods which make it much easier to build abstractions around the various configuration files on the machines.
Also includes some various quality of life fixes such as removing a random string that we had in the integration tests, minor documentation and formatting fixes here and there.
Closes #31

feat(slurm_ops): add cgroup configuration manager

---

dev-requirements.txt
lib/charms/hpc_libs/v0/slurm_ops.py
tests/unit/test_slurm_ops.py

This PR introduces initial support for managing JWT keys within `slurm_ops`. It's similar to the `_MungeKeyManager` class, but with the exception that it uses the [`cryptography`](https://cryptography.io/en/latest/) module to generate the key rather than a dedicated tool. Ideally we'll eventually use a dedicated tool - something like `jwtctl` - but that's for next cycle.
Also, this PR makes the small change of generating a `StateSaveLocation` directory for Slurm. The Debian package doesn't do this, so after install the `_AptManager` will create the `var/lib/slurm/slurm.state` directory that can be used for stashing the key and then exporting across the cluster. There doesn't seem to be an agreed upon standard, so I just chose the dirname `slurm.state` since it's clear that this is the …

feat(slurm_ops): implement initial jwt key manager

---

tox.ini

All of the Charmed HPC tox instances use `fmt`, not `format`. Switching back to `fmt` to that devx is consistent across Charmed HPC repos.
Misc. changes:
- Add periods to the end of each environment description.
Also, this PR highlights that we need to put together a spec for what HPC team tox files should look like. Should make some time at either leading up to roadmap or during the engineering sprint when we have the team together in-person.

fix: format -> fmt

---

CONTRIBUTING.md
README.md

This PR fleshes out the README and CONTRIBUTING documentation for `hpc-libs` so that it is inline with the other Charmed HPC repositories. This will help with discovery as well as informing people new to Charmed HPC to what hpc-libs actually is :shipit: 
_Who doesn't love badges and emojiis??_

docs: replace template README and CONTRIBUTING with hpc-libs specific ones

---

dev-requirements.txt
lib/charms/hpc_libs/v0/slurm_ops.py
tests/integration/test_hpc_libs.yaml
tests/unit/test_slurm_ops.py

This PR enables the `slurm_ops` lib to correctly set the user, group, and mode on files owned by Slurm. Originally, we had everything owned by `root` which isn't _bad_, but it's encourage that files like _slurm.conf_ and _jwt_hs256.key_ are owned by the dedicated system user `slurm` instead.
The PR adds public `user` and `group` properties that (a) be used to retrieve the `user` and `group` for configuration options such as `SlurmUser` and (b) pushes down to the configuration managers so that `slurmutils` can assign the proper access permissions to the configuration files.
Currently a draft because this PR needs PR https://github.com/charmed-hpc/slurmutils/pull/24 to land since it introduces the mode, user, and group setting features to slurmutils.

feat(slurm_ops): set correct permissions on files owned by Slurm

---

.github/workflows/ci.yaml
.github/workflows/nightly-TICS.yaml
.github/workflows/release-libs.yaml
.gitignore
tox.ini

- Fixes the CI pipeline, since the recent upgrade to 24.04 broke it.
- Adds a TiCS action that runs once every day.

ci: fix CI pipeline and add TiCS analysis action

---

lib/charms/hpc_libs/v0/slurm_ops.py
pyproject.toml
tests/unit/test_slurm_ops.py

This PR adds support for setting the `MYSQL_UNIX_PORT` environment variable needed by slurmdbd to connect to MySQL via a unix socket, and it adds configs for expanding the allowed amount open files at once.
This PR also improves the testing coverage of `_AptManager` by mocking several of the installation steps such as configuring apt to use the Ubuntu HPC PPA, writing security configurations, overriding service files, etc. It refactors the install function to (a) lower the cyclomatic complexity of `install` - less if/else in a single function - and (b) very easy to unit test.
* Configure black's target version to be py310 so that we can use match/case. [Python 3.8 is also EOL](https://endoflife.date/python), and we're not targeting any bases that use Python 3.8 by default.
* Simplify unit …

feat(slurm_ops): loosen environment variable rules and configure openfile limits

---

lib/charms/hpc_libs/v0/slurm_ops.py
tests/unit/test_slurm_ops.py

This PR implements the necessary fixes needed for `slurm_ops` to unblock https://github.com/charmed-hpc/slurm-charms/pull/35. The PR also bumps the `LIBPATCH` version to `8`.
* Fixes #52 
* Fixes #51 
* Fixes #50 
* Fixes #49 
* Fixes #48
* Fixes #47 
* Fixes #46

fix(slurm_ops): implement feedback from slurm-charms PR #35

---

lib/charms/hpc_libs/v0/slurm_ops.py
lib/charms/operator_libs_linux/v0/apt.py
tests/integration/slurm_ops/test_manager.py
tests/integration/test_hpc_libs.yaml
tests/unit/test_slurm_ops.py

> This PR is currently a draft because the apt charm library does not work on Noble based machines. Related bug report: https://github.com/canonical/operator-libs-linux/issues/135.
>
> Will do the version bump after apt charm library issues are fixed and the PR has been approved.
This PR introduces the `SackdManager` class which can be used in a downstream sackd-operator to manage the `sackd` service on machines.
BREAKING CHANGES: This PR drops the PPA `ubuntu-hpc/slurm-wlm-23.02` as it doesn't provide a `sackd` package, and the Slurm version that we can pull from Universe on Noble is newer than what is provided by the PPA. The `ubuntu-hpc/slurm-wlm-23.02` PPA also doesn't provide any packages that work on Noble.
Dropping this PPA means that you will now get an older version of Slurm on …

feat(slurm_ops)!: implement SackdManager for `sackd` service

---

lib/charms/hpc_libs/v0/slurm_ops.py

Updates `PYDEPS` in `slurm_ops` from `"slurmutils~=0.10.0"` to `"slurmutils<1.0.0,>=0.11.0"` so latest `slurmutils` in the 0.x version series is used.
Follows discussion around version bumps needed for the latest GRES file editor.

chore(slurm_ops) bump `slurmutils` to `<1.0.0,>=0.11.0`

---

lib/charms/hpc_libs/v0/slurm_ops.py
tests/integration/slurm_ops/test_manager.py
tests/unit/slurm_ops/test_apt.py
tox.ini

This PR adds the `slurm-client` package to the installed package set for the `SlurmdManager` class. Installing this package on slurmd nodes will enable cluster users and admins to call common commands such as `srun` and `sbatch` from within their workloads.
* Fixes #62 
* Renames the `static` environment in _tox.ini_ to `typecheck`. Brings it forward for our standards for other repositories.

fix(slurm_ops): install `slurm-client` package on slurmd nodes

---

lib/charms/hpc_libs/v0/slurm_ops.py
tests/integration/slurm_ops/test_manager.py

This PR updates `_ServiceManager` to more closely align with the API of the `systemctl` command. It uses patches from #67 to add the the `start`/`stop` methods, and switch `reload-or-restart` for plain ole `restart`. It also updates the integration tests to use `.start()` to start slurmctld instead of `.enable()`.
@jamesbeedy added you as a co-author of this PR.

feat(slurm_ops): have `_ServiceManager` mirror systemctl command API

---

.github/workflows/ci.yaml
lib/charms/hpc_libs/v0/slurm_ops.py
pyproject.toml
tox.ini

This PR removes the `--now` flag from `_SystemctlServiceManager` and enables static type checking in our CI pipeline for pull requests. As part of improving the static type checking, I also added some required type annotations.

fix(slurm_ops): remove `--now` flag from enable/disable

---

lib/charms/hpc_libs/v0/slurm_ops.py

These changes expose jwt_keyfile path as a public
property of the _JWTKeyManager.

enhancement: expose jwt_keyfile path

---

dev-requirements.txt
lib/charms/hpc_libs/v0/slurm_ops.py

This PR bumps the version of `slurm_ops` to 0.16.
Update cryptography to 44.0.1 to mitigate CVE-2024-12797 due to the cryptography wheel from PyPI shipping a statically linked version of OpenSSL.

chore(slurm_ops): bump `slurm_ops` to 0.16

---

lib/charms/hpc_libs/v0/slurm_ops.py

This PR bumps the LIBPATCH version of `slurm_ops` to 17.

chore(slurm_ops): bump `slurm_ops` to 0.17

---

lib/charms/hpc_libs/v0/slurm_ops.py
tests/unit/slurm_ops/test_config.py

Exposes the `ARGS` environment variable for `prometheus-slurm-exporter` to be able to pass arguments to the daemon.
Need to add tests for this.
#77 
Documentation was added to the exposed methods themselves.

feat: Expose CLI arguments for prometheus exporter daemon

---

src/hpc_libs/slurm_ops.py

Enable automatic restart of slurmctld on its systemd service file in case of failure, which
could happen if slurmctld tries to query slurmdbd while its backing database is not yet ready.
Only internal change.

fix: enable automatic restart of slurmctld in case of failure

---

README.md

The `Release` badge was broken due to the removal of the `release-libs` workflow after converting `hpc_libs` from a dummy charm to a proper Python package.
[//]: # (Please link to related issues, pull requests, and discussions here. If your PR has no related issues, PRs, or discussions, please provide a justification for this PR here instead.)
There is no open issue, but you can see that the `Release` badge is …

fix(docs): remove broken badge from README

---

pyproject.toml

Fixes the classifier license which was incorrectly using LGPL v3.
Just a metadata fix.

fix: use correct Apache license in the project classifiers

---

pyproject.toml
src/hpc_libs/utils.py
tests/unit/utils/test_refresh.py
uv.lock

This PR adds the `refresh` utility decorator and `StopCharm` exception. `refresh` can be used to either capture raised `StopCharm` exceptions and set the wrapped status as a high-priority status message, or `refresh` can be used to generate a charm-specific refresh decorator that will run a holistic status check at the of each event handler execution. For example:
```python
import ops
from hpc_libs.utils import …
```

feat: add `refresh` and `StopCharm` utilities

---

src/hpc_libs/utils.py

This PR modifies the `refresh` utility to accept generic types that are bound to `ops.CharmBase`. This modification is required to use "forward references" for annotating the `check` function with a specific charm class rather than the `ops.CharmBase` base class. 
For example, by using a generic annotation on `refresh`, we can pass `SlurmctldCharm` as the type rather than just `ops.CharmBase`:
```python
import ops …
```

feat(utils): make `refresh` accept generic types bound to ops.CharmBase

---

src/hpc_libs/machine/env.py
tests/unit/machine/test_env.py

This PR modifies the `EnvManager.set(...)` method to allow HPC charm authors to toggle environment variable quoting. Automatic quoting can interfere with important `slurmd` command line options such as `--conf`.
[//]: # (Please link to related issues, pull requests, and discussions here. If your PR has no related issues, PRs, or discussions, please provide a justification for this PR here instead.)
- Fixes #99 …

fix(machine/env): support toggling automatic quoting

---

src/hpc_libs/errors.py

This PR adds the custom `IngressAddressNotFoundError` exception to `hpc_libs`.
This exception is commonly used within charms such as `slurmdbd` and `slurmctld` for getting the public address of units. Moving this exception's definition to `hpc_libs` de-duplicates it's definition within the Slurm charms monorepo, and it reduces the amount of cut-and-paste we'd need to do each time we are required to change the …

feat(errors): add custom `IngressAddressNotFoundError` exception

---

src/hpc_libs/interfaces/__init__.py
src/hpc_libs/interfaces/base.py
src/hpc_libs/interfaces/slurm/common.py
src/hpc_libs/interfaces/slurm/slurmd.py
src/hpc_libs/interfaces/slurm/slurmdbd.py
src/hpc_libs/utils.py
tests/unit/interfaces/sackd/test_sackd.py
tests/unit/interfaces/slurmd/test_slurmd.py
tests/unit/interfaces/slurmdbd/test_slurmdbd.py
tests/unit/interfaces/slurmrestd/test_slurmrestd.py
tests/unit/utils/test_reconfigure.py
tests/unit/utils/test_refresh.py

This PR introduces three major changes:
1. Inverts the `status_when` conditions to `status_unless`. This change was made to improve the readability of conditions for working with event handlers.
2. Adds a `reconfigure` utility that works similar to the `refresh` utility. This feature is being introduced as the `slurmctld`, `slurmd`, and `slurmdbd` operators all share common boilerplate for a `reconfigure` …

feat: invert condition checks and add granular integration validators

---

src/hpc_libs/interfaces/slurm/sackd.py
tests/unit/interfaces/sackd/test_sackd.py

This PR adds an application data validator to the `sackd` interface to prevent race conditions where integration data arrives before the `controllers` field has been set to a valid `--conf-server` value.
[//]: # (Please link to related issues, pull requests, and discussions here. If your PR has no related issues, PRs, or discussions, please provide a justification for this PR here instead.)
Related to ongoing …

feat(interfaces/sackd): add app data validator

---

src/hpc_libs/interfaces/__init__.py
src/hpc_libs/interfaces/base.py

This PR exposes the `load_secret` and `update_secret` functions as top-level functions - e.g. `from hpc_libs.interfaces import load_secret, update_secret` - so they can be used within our charms which managed their own secrets. This is helpful for cutting down on repetitive boilerplate within charms where access secrets directly.
Other changes:
- Updated `load_secret` to handle `ops.ModelError` when the model does …

feat(interfaces): expose `load_secret` and `update_secret` as top-level functions

---

pyproject.toml
src/hpc_libs/interfaces/base.py
src/hpc_libs/interfaces/slurm/common.py
src/hpc_libs/interfaces/slurm/oci_runtime.py
src/hpc_libs/interfaces/slurm/slurmd.py
src/hpc_libs/interfaces/slurm/slurmdbd.py

Revisions to the new `StoredState` following input from @NucciTheBoss. The scope of the variable is reduced (`stored_state` -> `_stored`) and the comment calling the solution a "temporary fix" is reworded to "workaround", as this could be in place for longer than anticipated.
[//]: # (Please link to related issues, pull requests, and discussions here. If your PR has no related issues, PRs, or discussions, please …

fix: reduce scope of interface StoredState and reword comment
